
CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    active   BOOLEAN             DEFAULT TRUE                   NOT NULL,
    account_expired     BOOLEAN  DEFAULT FALSE                  NOT NULL,
    account_locked      BOOLEAN  DEFAULT FALSE                  NOT NULL,
    credentials_expired BOOLEAN  DEFAULT FALSE                  NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);
ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);

CREATE TABLE encomenda
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  UUID,
    nome_remetente        VARCHAR(255),
    nome_destinatario     VARCHAR(255),
    descricao             VARCHAR(255),
    tipo_pacote           VARCHAR(255),
    origem_logradouro     VARCHAR(255),
    origem_numero         VARCHAR(255),
    origem_cidade         VARCHAR(255),
    origem_estado         VARCHAR(255),
    origem_codigo_postal  VARCHAR(255),
    destino_logradouro    VARCHAR(255),
    destino_numero        VARCHAR(255),
    destino_cidade        VARCHAR(255),
    destino_estado        VARCHAR(255),
    destino_codigo_postal VARCHAR(255),
    valor_frete           DECIMAL(10, 2),
    usuario_id            BIGINT,
    CONSTRAINT fk_encomenda_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

--    FOREIGN KEY (usuario_id) REFERENCES usuario(id),
--    PRIMARY KEY (id)
--);





